name: opacity_button
description: Opacity Button which make able to convert any widget to button with opacity animation.
version: 1.0.0
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
