name: opacity_button
description: Opacity Button whcih help us to convert any widget to button (opacity)
version: 1.0.0
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
